import type { Activity } from "./types";

export const activities: Activity[] = [
  {
    id: "1",
    name: "Morning Run",
    sportType: "Run",
    distanceKm: 8.2,
    durationMin: 42,
    averagePace: "5:07/km",
    elevationGainM: 72,
    averageHeartrate: 151,
    calories: 615,
    date: "2026-05-10",
    aiBrief: {
      summary: "Allenamento aerobico solido con intensità moderata e ritmo abbastanza stabile.",
      intensityScore: 6,
      fatigueScore: 5,
      recoveryAdvice: "Considera una sessione leggera o mobilità se senti gambe pesanti.",
      positivePoints: ["Buon volume per la settimana", "Frequenza cardiaca coerente con un medio leggero"],
      warnings: ["Evita di sommare un altro lavoro intenso nelle prossime 24 ore"],
      nextWorkoutSuggestion: {
        type: "easy_run",
        durationMinutes: 45,
        intensity: "low",
        reason: "Recupero attivo dopo un carico moderato.",
      },
    },
  },
  {
    id: "2",
    name: "Lunch Ride",
    sportType: "Ride",
    distanceKm: 31.4,
    durationMin: 76,
    averagePace: "24.8 km/h",
    elevationGainM: 360,
    averageHeartrate: 143,
    calories: 860,
    date: "2026-05-08",
    aiBrief: {
      summary: "Uscita endurance efficace, con dislivello utile senza picchi eccessivi.",
      intensityScore: 5,
      fatigueScore: 4,
      recoveryAdvice: "Idratazione e carboidrati leggeri aiutano a chiudere bene la giornata.",
      positivePoints: ["Buona continuità di pedalata", "Carico cardiovascolare controllato"],
      warnings: ["Occhio al recupero se domani aggiungi corsa"],
      nextWorkoutSuggestion: {
        type: "mobility",
        durationMinutes: 25,
        intensity: "low",
        reason: "Scaricare anche e polpacci dopo bici e corsa ravvicinate.",
      },
    },
  },
  {
    id: "3",
    name: "Upper Body Strength",
    sportType: "Strength",
    distanceKm: 0,
    durationMin: 48,
    elevationGainM: 0,
    averageHeartrate: 118,
    calories: 390,
    date: "2026-05-07",
    aiBrief: {
      summary: "Sessione forza ben piazzata per supportare postura e resilienza generale.",
      intensityScore: 4,
      fatigueScore: 3,
      recoveryAdvice: "Se senti spalle affaticate, tieni il prossimo lavoro upper più tecnico.",
      positivePoints: ["Buon bilanciamento con il lavoro endurance", "Stress metabolico contenuto"],
      warnings: ["Mantieni tecnica pulita sulle ultime serie"],
      nextWorkoutSuggestion: {
        type: "easy_run",
        durationMinutes: 35,
        intensity: "low",
        reason: "Aggiungere volume facile senza interferire con il recupero muscolare.",
      },
    },
  },
  {
    id: "4",
    name: "Evening Walk",
    sportType: "Walk",
    distanceKm: 4.6,
    durationMin: 52,
    averagePace: "11:18/km",
    elevationGainM: 28,
    averageHeartrate: 94,
    calories: 210,
    date: "2026-05-05",
    aiBrief: {
      summary: "Camminata utile per recupero attivo e spesa energetica a bassa intensità.",
      intensityScore: 2,
      fatigueScore: 1,
      recoveryAdvice: "Ottima scelta nei giorni tra sessioni più impegnative.",
      positivePoints: ["Basso stress", "Favorisce continuità e recupero"],
      warnings: [],
      nextWorkoutSuggestion: {
        type: "tempo_run",
        durationMinutes: 40,
        intensity: "moderate",
        reason: "Hai margine per inserire un lavoro controllato se ti senti fresco.",
      },
    },
  },
];
